package Exam.Done.Threads.Basics.Threads.Methods;

public class Yield {

    static class Tushar extends Thread {

        Tushar(String name) {
            super(name);
        }

        @Override
        public void run() {
            for (int i = 0; i < 10; i++) {
                System.out.println(Thread.currentThread().getName() + " Running.... ");
                Thread.yield();
            }

        }
    }


    public static void main(String[] args) {

        Tushar t = new Tushar("Tushar");
        Tushar v = new Tushar("Vijay");

        t.start();
        v.start();

    }


}


/*
Without Yield()
Tushar Running....
Tushar Running....
Tushar Running....
Tushar Running....
Tushar Running....
Tushar Running....
Tushar Running....
Tushar Running....
Tushar Running....
Tushar Running....
Vijay Running....
Vijay Running....
Vijay Running....
Vijay Running....
Vijay Running....
Vijay Running....
Vijay Running....
Vijay Running....
Vijay Running....
Vijay Running....

With Yield()
Tushar Running....
Vijay Running....
Tushar Running....
Vijay Running....
Vijay Running....
Tushar Running....
Vijay Running....
Tushar Running....
Vijay Running....
Tushar Running....
Tushar Running....
Vijay Running....
Tushar Running....
Tushar Running....
Vijay Running....
Tushar Running....
Vijay Running....
Tushar Running....
Vijay Running....
Vijay Running....
 */